AKS: Add-On Profiles (#1751)
* Added kubernetes_cluster advanced network creation

* Changed network_profile from TypeSet to TypeList

* Added kubernetes_cluster advanced network creation

* Changed network_profile from TypeSet to TypeList

* Updated ForceNew attributes on kubernetes_cluster.network_profile params

* Added advanced network read functionality

* Added tests for kubernetes_cluster.network_profile

* Fixed indentations

* Fixed function name in tests

* Fixed property name in test

* Fixed variable name

* working on data source for kubernetes cluster

* Fixed issue with datasource not working

* Added network_policy and fixed read

* Removed network_policy as unsupported

* Added example of advanced networking

* Added test for data_source

* Made address space more sensible

* Removing kubenet test.
This is default when network_profile is not specified.
We already test this.

* Made network_plugin a mandatory field.
Better to make this explicit.

* Updated documentation to include network_profile

* Fixing the build

* Added ForceNew to network_profile

* Made the docs a little clearer

* Documenting a required field

* Rephrasing the data sources

* Making the `network_profile` block computed

Tests pass:

```
$ acctests azurerm TestAccAzureRMKubernetesCluster_basic
=== RUN   TestAccAzureRMKubernetesCluster_basic
--- PASS: TestAccAzureRMKubernetesCluster_basic (1329.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	1329.613s
```

* Fixing the field we're asserting on

* Conditionally expanding the network_profile block.

The ip fields are now Computed too

* Validation to ensure that a Subnet ID is assigned to the cluster when the network_profile blocks specified

Example:

```

Error: Error running plan: 1 error(s) occurred:

* azurerm_kubernetes_cluster.test: 1 error(s) occurred:

* azurerm_kubernetes_cluster.test: If a `network_profile` block is specified, the Agent Pools must be attached to a Subnet

```

* Updating the documentation to mention the new behaviour

* Adding independent tests for Kubenet and Azure networking profiles

* Conditional validation of the `docker_bridge_cidr`, `dns_service_ip` and `service_cidr` fields.

* Updating the docs

* Fixing the tests

* Adding back in the changes from PR #1502 since they were lost in the merge

* Renaming the methods to `addonProfiles` to match the sdk

* fixing the quotes