App Service / Function Apps: support for updating (#1125)
* Enabling updates for App Services, which breaks the following test:

```
$ acctests azurerm TestAccAzureRMAppService_tagsUpdate
=== RUN   TestAccAzureRMAppService_tagsUpdate
--- FAIL: TestAccAzureRMAppService_tagsUpdate (109.41s)
	testing.go:513: Step 1 error: Check failed: Check 2/4 error: azurerm_app_service.test: Attribute 'tags.%' expected "2", got "1"
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-azurerm/azurerm	109.444s
```

* Updating the app service properties on an update

```
$ acctests azurerm TestAccAzureRMAppService_tagsUpdate
=== RUN   TestAccAzureRMAppService_tagsUpdate
--- PASS: TestAccAzureRMAppService_tagsUpdate (144.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	144.156s
```

* Added a test to handle updating function apps

* Ensuring we update function apps

* Updating the docs to remove the newly non-forcenew fields

* Ensuring we always update the app_settings

```
$ acctests azurerm TestAccAzureRMFunctionApp_siteConfigMulti
=== RUN   TestAccAzureRMFunctionApp_siteConfigMulti
--- PASS: TestAccAzureRMFunctionApp_siteConfigMulti (225.65s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	225.693s
```